### ISSUE TITLE
FATAL ERROR: RedirectsFrontEnd.php on line 30

### ISSUE THREAD

**Issue by haleeben** [kylephillips/wp-nested-pages#145]
Hi 

In version 1.5.3 there is an error in the code that causes a FATAL ERROR.

The classs method `removeParentSlugs` in the file `app/RedirectsFrontEnd.php` returns a call to itself if the `$parent_type` is true

`private function removeParentSlugs($post, $slug)
	{
		$parent_type = get_post_type($post->post_parent);
		if ( $parent_type == 'np-redirect' ){
			$parent_post = get_post($post->post_parent);
			$slug = str_replace($parent_post->post_name . '/', '', $slug);
			return $this->removeParentSlugs($parent_post, $slug);
		}
		return $slug;
	}`

**Comment by dtwist** [comment]
I just arrived to report the same issue. To elaborate on @haleeben 's comments:

To repeat:
1) Create fresh WP install, install nested pages plugin.
2) Go to "All Pages" and create a new link, linking to the "sample page" page.
3) Reload "All Pages"
*NOTE that this triggers a fatal error. X-debug will report "Maximum function nesting level of '256' reached, aborting! in /path/to/wp/wp-includes/post.php on line 421"*

The issue here is that the removeParentSlugs() method is recursing with a post object that is identical to the post object it was called with when the provided post object has no parent. The call to get_post() returns the current WP post object when the provided id is 0, and you get infinite recursion. 

@haleeben 's proposed solution prevents the error by removing the recursive method call, but that will cause issues with np-redirect post objects that DO have parents. The fix I've employed is to wrap the bulk of the method in an if statement testing the post_parent value:

```php
		if ( $post->post_parent > 0 ) {
			$parent_type = get_post_type($post->post_parent);
			if ( $parent_type == 'np-redirect' ){
				$parent_post = get_post($post->post_parent);
				$slug = str_replace($parent_post->post_name . '/', '', $slug);
				return $this->removeParentSlugs($parent_post, $slug);
			}
		}
		return $slug;
```

Pull request to follow.

Cheers, and thanks for all the hard work on this plugin! :)
