### ISSUE TITLE
Key of meta is changed

### ISSUE THREAD

**Issue by wgroenewold** [kylephillips/wp-nested-pages#189]
I used some meta (label and classes) in a custom walker class. Since the upgrade to the latest version of Nested Pages the key of the meta is changed from np_nav_css_classes and np_nav_title to _np_nav_css_classes and _np_nav_title. It would be nice to address this in the changelog next time 🙂

**Comment by kylephillips** [comment]
Point taken. There shouldn't be a next time since this was a one time change, noted in the changelog below:

* Custom fields generated by the plugin converted to hidden fields, preventing them from displaying in the post custom field meta box

I'll be more explicit if there are more custom field changes.
