### ISSUE TITLE
Querying Nested Pages Links in theme

### ISSUE THREAD

**Issue by fabiangigler** [kylephillips/wp-nested-pages#205]
Hi, thanks for the awsome plugin, I use it in almost all projects.
Is there any possibility to get links added in the nested pages editor in a query on the frontend? I would want to list all pages that have a specific parent page, including any nested pages links.

Let me know if this is possible already, or if you would consider it a enhancement to be added in the future.
Any pointers into implementing this myself would also help. Thank you!

**Comment by lkraav** [comment]
@fabiangigler I for one have trouble understanding what you're looking to do. Rephrase?

**Comment by kylephillips** [comment]
I understand what you're looking for. 

I have a premium version of the plugin in development where this feature will more than likely be included.

If you need to implement before then, I would suggest using a WP_Query, and including the post types page and np-redirect. 

You'll probably want to look at the custom meta stored by Nested Pages in order to display relevant data for the links. This gets  a little complicated because they're stored similarly to native menu items, with relationships.
