### ISSUE TITLE
Feature Request: Ability to Disable Cloning

### ISSUE THREAD

**Issue by opensaurusrex** [kylephillips/wp-nested-pages#243]
Can you add the ability to disable the cloning feature?

The rest is  awesome. I have been asked by my client to make it so that the content writers will need to use the plugin I designed for them to manage the content of the releases because it clones and/or rewrites specific post meta and the guid of the new group of posts for the new version that they are creating pages for.

I checked in settings but didn't see a configuration for it. I hope you can add this in a future version.

Thanks!

**Comment by kylephillips** [comment]
Rather than making this a setting, I've added filters for each of the actions/links displayed in a row. Two parameters are passed, a boolean (whether to hide/show the link), and the post type (string, post type name).

This will be included in the next release. [Here is a reference](https://gist.github.com/kylephillips/91972d58766faced55eff6ed1579796b). 

You'll be able to add the following to your functions.php to disable the clone link:

```
// Hide/Show the "Clone" link
add_filter('nestedpages_row_action_clone', 'nestedPagesClone', 10, 2);
function nestedPagesClone($include, $post_type)
{
	return true;
}
```

**Comment by kylephillips** [comment]
Closed  in 3b13cb4376cb3499e7790c70283de9c128f998f2

**Comment by opensaurusrex** [comment]
Is this in v3.0.7 or will it be in v3.0.8, whenever that is planned to be released?

**Comment by walle89** [comment]
Is it possible to use skip requirement of `edit_pages` and `edit_posts`? Our site doesn't use posts and have disabled it and pages are restricted to a few persons. I want to use this plugin for a selected few custom post types.
