### ISSUE TITLE
feature request: Add link to CPT

### ISSUE THREAD

**Issue by typometre** [kylephillips/wp-nested-pages#329]
Is there a way to enable the add link feature to CPT.
The same as it's done for page.
An option in the CPT Nested Page settings to activate that would be great.

As CPT doesn't create a menu yet, I understand, it's not a priority but I have done an automatic menu from part of the nested hierarchy by hand in my theme and retreived the links in it. I would like the same for CPT but the insert link is not there on the CPT nested pages.  

Best regards for the work on nested pages and hope this could be added.

**Comment by typometre** [comment]
Have found how to add the add link button by deleting the check for pages only line 28 of listing.php but the links only display when added.
And have seens that its work in front with my custom code.
But I can't find where to make the links appear by default on the listing of a CPT.

**Comment by typometre** [comment]
It works by adding `$post_type[] = 'np-redirect';` line 92 of ListingQuery.php

An option to toogle this on the CPT settings would be really great.

**Comment by typometre** [comment]
I have forked the plugin to make theses changes
https://github.com/typometre/wp-nested-pages
Hope an option could be added in regular version.

**Comment by kylephillips** [comment]
Links are associated with pages only due to their primary use being within the generated nav menu.

That said, if you'd like to include links in other post types, a couple of filters have been added and will be in the next release. Example usage [can be referenced in this gist](https://gist.github.com/kylephillips/28e2dd35b2923a672f5122fff93aeaad).

If you include links in the pages interface, and other custom post type(s), you may have unexpected results with ordering and display.

**Comment by typometre** [comment]
Hi,
Yes thanks the filters are really helpful. 
In front, I have a custom menu in sidebar with my cpt and links from np-redirect and the ordering and display works just fine.
That's really useful. Before I was obliged to create a post and redirect it and it's really better to directly add an external link and avoid redirection.
Best regards
